<!DOCTYPE html>
<html lang="fr">

<head>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>

<body>
	<header>
	<div class="container">
		<a class="link name" href="#">Hélène Patat</a>
		<nav>
			<a class="link" href="#">Expériences</a>
			<a class="link" href="#">Etudes</a>
			<a class="link" href="#">Compétences</a>
			<a class="link" href="#">Centre d'intérêts</a>
		</nav>
	</div>
	</header>
	<main></main>
	<footer>
		<p>Ce web CV a été réalisé par Léti-dev.</p>
	</footer>
</body>

</html>